name: Retag nginx image
on:
  push:
    branches:
      - ikenna

jobs:
  retag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Retag to ikenna
        run: |
          docker pull nginx:alpine
          docker tag nginx:alpine officialdarnyc/nginx:ikenna
          docker push officialdarnyc/nginx:ikenna
          
