name: Retag nginx image
on:
  push:
    branches:
      - ikenna

  workflow_dispatch:

jobs:
  retag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version number
        run: |
          $version = "$($Env:GITHUB_RUN_NUMBER)"
          echo $version
          echo "VERSION_NUMBER=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Retag image
        run: |
          docker pull nginx:alpine
          docker tag nginx:alpine officialdarnyc/nginx:v${{ env.VERSION_NUMBER }}
          docker push officialdarnyc/nginx:v${{ env.VERSION_NUMBER }}

      #- name: 'Update MAJOR version number'
       # uses: hmanzur/actions-set-secret@v2.0.0
       # with:
        #  name: 'MAJOR'
        #  value: (1+${{ secrets.MAJOR }})
        #  repository: ${{ github.repository }}
        #  token: ${{ secrets.REPO_ACCESS_TOKEN }}

          
